### ISSUE TITLE
Built documentation outdated

### ISSUE THREAD

**Issue by hoechenberger** [hddm-devs/hddm#36]
The documentation at http://ski.clps.brown.edu/hddm_docs/genindex.html is not up-to-date (based on HDDM 0.5.3)
Maybe this repository should be set up to work with readthedocs.org for automated doc generation?

**Comment by twiecki** [comment]
Thanks for the comment. It actually is up-to-date, just the version string is outdated (easy to fix). It's quite easy already to recompile and update.

**Comment by hoechenberger** [comment]
Oh, I didn't realize it was just the version string, thanks for the quick response! :)
