### ISSUE TITLE
Is it possible to create a docker image for hddm to enhance reproducibility?

### ISSUE THREAD

**Issue by hcp4715** [hddm-devs/hddm#46]
Dear @frankmj @twiecki ,
Recently I attended a workshop about open science in neuroscience, and found the docker is a really cool software to enhance reproducibility.

So I am wondering are you going to create a hddm docker image. I guess then people don't need to ask about the python version and install problem over and over again ;-).

Best,
Chuan-Peng

**Comment by twiecki** [comment]
I think this would be a great contribution, I won't have time to do it
myself, however.

**Comment by twiecki** [comment]
This is available now `docker pull madslupe/hddm`
