### ISSUE TITLE
Deprecation Warnings and PyMC

### ISSUE THREAD

**Issue by Oneiromancer** [hddm-devs/hddm#49]
I am getting deprecation warnings for pymc, which I can see is now deprecated by PyMC3, when calling `model_group_basic.sample(num_samples,burn=num_burn,dbname=model_group_basic_traces,db='pickle')`
> C:\Anaconda3\lib\site-packages\pymc\Node.py:403: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
>   self.__name__ = input['__name__']
>C:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:224: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

I noticed HDDM has not been updated in several years, and just wondering whether to expect upgrades soon or to remain on the deprecated pymc.

**Comment by twiecki** [comment]
There will be a new release soon but we won't make it depend on pymc3. pymc2 is still being maintained. Can you open an issue there, as it's not an hddm issue?
