### ISSUE TITLE
Error in installing hddm: module 'pymc' has no attribute 'stochastic_from_dist'

### ISSUE THREAD

**Issue by ChenghuFeng** [hddm-devs/hddm#87]
Hi here,
I am a beginner in python, and I try to import hddm I met following problem, which seem caused by pymc. And I try to reinstall pymc many times, but it does not work. It is thankful if someone could solve this problem. (My python version is 3.10, and I can successfully import numpy, pandas, pymc[some warning])

- HalfCauchy = pm.stochastic_from_dist(name="Half Cauchy",
- AttributeError: module 'pymc' has no attribute 'stochastic_from_dist'

(some error happens seem it could not find pymc's attribute stochastic_from_dist)
- HalfCauchy = pm.stochastic_from_dist(name="Half Cauchy",
                                     random=centered_half_cauchy_rand,
                                     logp=centered_half_cauchy_logp,
                                     dtype=np.double)

**Comment by ChenghuFeng** [comment]
I  install a very new version pymc

**Comment by jesson3264** [comment]
> I install a very new version pymc

What's your pymc version, I has occoured the error, too.

**Comment by ChenghuFeng** [comment]
https://huchuanpeng.com/post/2019-04-29-how-to-install-and-use-hddm/

**Comment by ChenghuFeng** [comment]
@jesson3264  I finally run hddm by following Hu's guide. It's very simple, hope it helpful to u~ The website following is the guide  :)

https://huchuanpeng.com/post/2019-04-29-how-to-install-and-use-hddm/

**Comment by jesson3264** [comment]
> @jesson3264 I finally run hddm by following Hu's guide. It's very simple, hope it helpful to u~ The website following is the guide :)
> 
> https://huchuanpeng.com/post/2019-04-29-how-to-install-and-use-hddm/

Thank you very much!

**Comment by mrinmayik** [comment]
Hello!

Are there any suggestions for installing PyMC on a Mac (Monterey 12.6)? I'm using Python version 3.9.12.

When I try to install an older version of PyMC using the command `pip install pymc==2.3.8` (based on the suggestion [here](https://discourse.pymc.io/t/struggling-to-import-hddm-attributeerror-module-pymc-has-no-attribute-stochastic-from-dist/10069/3)) I get `ERROR: Failed building wheel for pymc` followed by a bunch of errors.

Any help is appreciated!

Thank you,
Mrinmayi
